name: Update OpenTabletDriver

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Flatpak and Flatpak-Builder
        run: |
          sudo add-apt-repository ppa:flatpak/stable -y
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Set up Flathub remote
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  
      - name: Install SDKs and Runtime
        run: |
          flatpak install flathub org.freedesktop.Platform//23.08 -y
          flatpak install flathub org.freedesktop.Sdk//23.08 -y
          flatpak install flathub org.freedesktop.Sdk.Extension.dotnet6//23.08 -y
          
      - name: Download OpenTabletDriver latest release
        run: |
          curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest \
          | grep "browser_download_url.*zip" \
          | cut -d '"' -f 4 \
          | wget -i -
          
      - name: Download flatpak-dotnet-generator.py script
        run: wget https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/dotnet/flatpak-dotnet-generator.py
      
      - name: Generate linux-x64.json
        run: python flatpak-dotnet-generator.py linux-x64.json ./OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --runtime linux-x64 --freedesktop 23.08
      
      - name: Generate linux-arm64.json
        run: python flatpak-dotnet-generator.py linux-arm64.json ./OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --runtime linux-arm64 --freedesktop 23.08
      
      - name: Replace json files
        run: |
          mv linux-x64.json ./sources/linux-x64.json
          mv linux-arm64.json ./sources/linux-arm64.json

      - name: Modify net.opentabletdriver.OpenTabletDriver.yaml
        run: |
          TAG=$(curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          sed -i "s/tag: .*/tag: $TAG/" net.opentabletdriver.OpenTabletDriver.yaml
          echo "# Generated by GitHub Actions. $(date -u +'%Y-%m-%d %H:%M:%S %Z')" >> net.opentabletdriver.OpenTabletDriver.yaml

  check_for_updates:
    runs-on: ubuntu-latest
    needs: update # This makes sure check_for_updates runs after update job

    strategy:
      matrix:
        branch: [ master ] # list all branches to check

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - uses: docker://ghcr.io/flathub-infra/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork net.opentabletdriver.OpenTabletDriver.yaml # replace with your manifest path
